name: Update Simple Index

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  GH_TOKEN: ${{ github.token }}
  AWS_S3_ENDPOINT_URL: https://86099e5f6de2cd6346db01f48072efa4.r2.cloudflarestorage.com
  MC_ALIAS: r2
  BUCKET: wheelhouse
  BUCKET_ACCESS_URL: https://wheelhouse.kafai.eu.org

jobs:
  deploy:
    name: Build Simple Index Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Minio CLI
        uses: hostwithquantum/setup-mc@main
        with:
          alias-name: ${{ env.MC_ALIAS }}
          alias-url: ${{ env.AWS_S3_ENDPOINT_URL }}
          alias-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          alias-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Connect Bucket
        run: mc alias set ${{ env.MC_ALIAS }} ${{ env.AWS_S3_ENDPOINT_URL }} ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dumb-pypi
        run: pip install dumb-pypi

      - name: Build Index
        run: |
          mc ls ${{ env.MC_ALIAS }}/${{ env.BUCKET }} --json | jq -c '{filename: .key, upload_timestamp: .lastModified|sub("\\.[0-9]*";"")|fromdate}' > package-list.jsonl
          cat package-list.jsonl
          dumb-pypi --output-dir build \
          --title "Odoo Contrib Pypi" \
          --packages-url ${{ env.BUCKET_ACCESS_URL }} \
          --package-list-json package-list.jsonl
        env:
          TZ: ETC/UTC

      - name: Upload Page Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
